### ISSUE TITLE
demo on how can be used

### ISSUE THREAD

**Issue by rakucmr** [dmitrymomot/kohana-acl#2]
How can be used? It replace Auth from kohana?

**Comment by dmitrymomot** [comment]
I'm sorry, but I speak english very bad
so I can't write userguide
I'll try to make demo in near future

<blockquote>
How can be used? It replace Auth from kohana?
</blockquote>

No, this module doesn't replace Auth. It works with drivers, also can use Kohana/Auth as driver.

**Comment by Mariyo** [comment]
Hi,
any news with demo?

**Comment by dmitrymomot** [comment]
@Mariyo this repo is not supported by me. Kohana has already died, so it has no sense.
I'm sorry.

**Comment by Mariyo** [comment]
Hi, 
I dont think, that Kohana has died. At least from [official forum](http://discourse.kohanaframework.org/), where are topics about planned PHP 7 support and milestones for next releases...
